-- Seed data for Income categories
-- console.log('Seeding categories...');

-- INSERT INTO categories (user_id, name, type, description, img_name)
-- VALUES 
--     (1,'Salary', 'Income', 'Debit', 'salary.png'),
--     (1,'Investment', 'Income', 'Credit', 'investment.png'),
--     (1,'Savings', 'Income', 'Credit', 'savings.png'),
--     (1,'Freelance', 'Income', 'Credit', 'freelance.png'),
--     (1,'Bonus', 'Income', 'Credit', 'bonus.png'),
--     (1,'Food', 'Expense', 'Cash', 'food.png'),
--     (1,'Transport', 'Expense', 'Cash', 'transport.png'),
--     (1,'Utilities', 'Expense', 'Cash', 'utilities.png'),
--     (1,'Rent', 'Expense', 'Cash', 'rent.png'),
--     (1,'Groceries', 'Expense', 'Cash', 'groceries.png'),
--     (1,'Entertainment', 'Expense', 'Cash', 'entertainment.png'),
--     (1,'Healthcare', 'Expense', 'Cash', 'healthcare.png'),
--     (1,'Education', 'Expense', 'Cash', 'education.png'),
--     (1,'Clothing', 'Expense', 'Cash', 'clothing.png'),
--     (1,'Subscriptions', 'Expense', 'Cash', 'subscriptions.png'),
--     (1,'Gifts', 'Expense', 'Cash', 'gifts.png'),
--     (1,'Travel', 'Expense', 'Cash', 'travel.png'),
--     (1,'Vacation', 'Expense', 'Cash', 'vacation.png'),
--     (1,'Insurance', 'Expense', 'Cash', 'insurance.png'),
--     (1,'Mobile Bill', 'Expense', 'Cash', 'mobile.png'),
--     (1,'Internet', 'Expense', 'Cash', 'internet.png'),
--     (1,'Sports', 'Expense', 'Cash', 'sports.png');
